### ISSUE TITLE
Notrium window size

### ISSUE THREAD

**Issue by nsajko** [verhoevenv/OpenNotrium#32]
The program window size should probably be adjustable, through a config
file in-game menu or something like that.
It was possible to run it fullscreen on Windows, right?

**Comment by Enet4** [comment]
This is a late reply, I admit. But changing the game resolution is already possible by modifying "cfg.cfg". This file configures the display resolution and sound/music switches. Take care when modifying it manually though, the game does not expect an aspect ratio different from 4:3.

**Comment by verhoevenv** [comment]
Unless someone objects, I'm going to close this issue in a week as it's already possible. We could make it a whole lot easier and safer to change the resolution, but that's another issue...

**Comment by verhoevenv** [comment]
Closing since it's not an issue
