### ISSUE TITLE
Bad textures in timer/counter 

### ISSUE THREAD

**Issue by Enet4** [verhoevenv/OpenNotrium#8]
The screenshots make the issue clear. This is happening in my 64-bit Linux machine. Whenever an item drop or combination is issued, the GUI uses the character tile image for the texture of anything in the counter.
![shot4](https://cloud.githubusercontent.com/assets/4738426/4495591/0bdb6044-4a5d-11e4-988b-a44ebe9b4502.png)
![shot5](https://cloud.githubusercontent.com/assets/4738426/4495593/113d702c-4a5d-11e4-9458-6b51c2587fd4.png)

**Comment by verhoevenv** [comment]
Fixed in #34
